
# Generated by ChatGPT on demand
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):
    dependencies = [
        ('timesheets', '0003_unit_max_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name='TAApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('TO_UC', 'Submitted to Unit Coordinator'), ('TO_HR', 'Forwarded to HR'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=12)),
                ('note', models.TextField(blank=True)),
                ('uc_note', models.TextField(blank=True)),
                ('hr_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ta_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='taapplication',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ta_applications', to='timesheets.unit'),
        ),
        migrations.AlterUniqueTogether(
            name='taapplication',
            unique_together={('applicant', 'unit', 'status')},
        ),
    ]
